### ISSUE TITLE
Add CORS header

### ISSUE THREAD

**Issue by splinter03** [ilpaolino/homeylocalapi#2]
Please add Access Control header to prevent CORS problems, when calling API from a different origin.

`Access-Control-Allow-Origin: *`

Thank you very much!

**Comment by ilpaolino** [comment]
Solved in 1.1.0 https://github.com/ilpaolino/homeylocalapi/commit/31fb26eaebe3b3320f136c62e0136e5533bfe266

**Comment by splinter03** [comment]
Hey Paolo, i've testet your changes, unfortunately it dosn't work as expected. The prefligt is answered correct but, but the browser blocked the proper GET request, cause the "Access-Control-Allow-Origin" header is missing. Could you please apply the new setting to the repsone-part and add the needed header. Thank you very much!

**Comment by ilpaolino** [comment]
Updated to version 1.1.2.
https://homey.app/it-it/app/dev.dadda.localapi/Local-API/test/
Can you try again?

**Comment by splinter03** [comment]
Works fine, thank you very much!
