### ISSUE TITLE
How to get it working

### ISSUE THREAD

**Issue by remcovaal** [ilpaolino/homeylocalapi#3]
Firstly, when activating the APP on Homey, I have to add "Access-Control-Allow-Origin" what value do I have to fill in

Then, if when ap enabled, I never get response via the suggested string http://[homey-ip]:[port]/key

**Comment by ilpaolino** [comment]
You can set `Access-Control-Allow-Origin` to `*` to allow requests from every IP.
To receive a response you MUST set a Respond in flows (How-To point 6 and 7)

I've updated the readme:
**How to use**
1. Install the app
2. Set up the app in the settings page and restart it
3. Create a new flow with the Local API app: remember to add the trigger card
4. Personalize the flow as you like
5. End the flow with at least one of the following cards:
6. Respond with ... (remember to add the JSON response)
7. Respond with 200
8. Save the flow and test it with a browser. The URL is http://homey-ip:<PORT>/endpoint-name

**Disclaimer**
Don't use this app to expose your Homey to the internet. Its use is intended for local network only.

**Comment by remcovaal** [comment]
How should the JSON response lookslike? As (even via telnet) the Homey does not respond.

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by remcovaal** [comment]
See crache reports. Hereby diagnostic ID 609baf60-439d-457e-8555-e6c220c41692

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by ilpaolino** [comment]
Can you try to change the server port? (use in example 3300 and restart the app after save settings).
Can you set the flow like the example in this page: https://community.homey.app/t/app-pro-local-api/70840/5 

Let me know

Paolo

**Comment by remcovaal** [comment]
App still craching

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by ilpaolino** [comment]
Are you sure you have changed the port and restart the app?

From homey's server I've got only this error in crash report:
```Emitted 'error' event on Server instance at:
    at emitErrorNT (node:net:1357:8)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  code: 'EACCES',
  errno: -13,
  syscall: 'listen',
  address: '0.0.0.0',
  port: 188
```

That error report me you're try using port 188 (which is already occupied by another service).

To restart the app you must go in settings and press "Restart App"

**Comment by remcovaal** [comment]
[Image.png]

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by ilpaolino** [comment]
I can't see the attachment here on github, can you post it on the homey support forum? https://community.homey.app/t/app-pro-local-api/70840/5

**Comment by remcovaal** [comment]
That attachment was nothing more than a proof Inadjuster the port number

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by ilpaolino** [comment]
I can only suggest you to uninstall and reinstall the app, because the crash report is related only to the server port.

If you need more support you can write me on the Homey Support forum, in the dedicated thread:
https://community.homey.app/t/app-pro-local-api/70840/5
 
Paolo
