### ISSUE TITLE
{"status":"not-found"}

### ISSUE THREAD

**Issue by betsim** [ilpaolino/homeylocalapi#6]
I installed Local API App for Homey, set the port to 5000, disabled CORS and restarted the app. 

If I try this request within an browser: `http://172.16.x.xx:5000/dingzSwitchEvent` or `get://172.16.x.xx:5000/dingzSwitchEvent` within Postman (with the full IP of course) the response is `{"status":"not-found"}`

edit: I have the new early 2023 pro

Can you help me?

**Comment by ilpaolino** [comment]
Hi, can you provide a screenshot of your Homey Advanced flow?

**Comment by betsim** [comment]
<img width="798" alt="Bildschirmfoto 2023-08-22 um 11 12 42" src="https://github.com/ilpaolino/homeylocalapi/assets/1453303/98393fa4-442e-47e6-8fa5-28d6211b6714">

**Comment by betsim** [comment]
I have figured out how to make a request with the local Homey IP via Logic > WebHook. Therefore, the use of Local API is no longer necessary for me.
